version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: rag-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      COHERE_API_KEY: ${COHERE_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      CORS_ORIGINS: http://localhost:3000,http://frontend:3000
    ports:
      - "8000:8000"

  # Next.js Frontend
  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: rag-frontend
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

# Usage:
# 1. Make sure .env has all required variables
# 2. Run: docker-compose up --build
# 3. Frontend: http://localhost:3000
# 4. Backend: http://localhost:8000
# 5. API Docs: http://localhost:8000/docs
#
# Note: Using Supabase for database (no local postgres needed)
# Workers run separately: cd workers && python ingest_notion.py